"""remove pswd from user and student table

Revision ID: 5610c7777d4a
Revises: cae905e7658d
Create Date: 2024-08-29 23:50:49.361566

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5610c7777d4a'
down_revision = 'cae905e7658d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.drop_column('password')

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=1000), nullable=False))

    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=1000), nullable=False))

    # ### end Alembic commands ###
