"""Initial migration for courses-->professor relationship

Revision ID: 95944c85721e
Revises: 19dfdf1935bf
Create Date: 2024-08-27 20:11:11.824974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95944c85721e'
down_revision = '19dfdf1935bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty_course',
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.PrimaryKeyConstraint('faculty_id', 'course_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faculty_course')
    # ### end Alembic commands ###
